export const RESET_REDUX_STATE = 'RESET_REDUX_STATE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const JWT_REFRESHED_SUCCESS = 'JWT_REFRESHED_SUCCESS';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const TOGGLE_REMEMBER_ME = 'TOGGLE_REMEMBER_ME';
export const UPDATE_PIN = 'UPDATE_PIN';
export const SAVE_USER_ONBOARDING = 'SAVE_USER_ONBOARDING';

export const PATCH_USER_BEGIN = 'PATCH_USER_BEGIN';
export const PATCH_USER_SUCCESS = 'PATCH_USER_SUCCESS';
export const PATCH_USER_ERROR = 'PATCH_USER_ERROR';
