export const GET_AUTHENTICATION_BEGIN = 'GET_AUTHENTICATION_BEGIN'
export const GET_AUTHENTICATION_SUCCESS = 'GET_AUTHENTICATION_SUCCESS'
export const GET_AUTHENTICATION_FAIL = 'GET_AUTHENTICATION_FAIL'

export const LOG_OUT = 'LOG_OUT'