export const LOGIN_PATH_NAME = '/login'
export const PASSWORD_RESET_PATHNAME = '/password-reset'
export const PASSWORD_RESET_COMPLETE_PATHNAME = '/resetpw'
export const LOGIN_PATH_NAMES = [LOGIN_PATH_NAME, PASSWORD_RESET_PATHNAME, PASSWORD_RESET_COMPLETE_PATHNAME]